### ISSUE TITLE
Looking for Prisma version

### ISSUE THREAD

**Issue by laohanme** [nainglinnkhant/shadcn-view-table#5]
This is great, so I was looking for example by using Prisma.

**Comment by nainglinnkhant** [comment]
I appreciate your interest in the project. Unfortunately, I've implemented the whole project with drizzle and there's no example for using Prisma. But hope these guides can help you.

https://www.prisma.io/docs/orm/more/migrating-to-prisma/migrate-from-drizzle
https://www.prisma.io/docs/orm/more/comparisons/prisma-and-drizzle

**Comment by laohanme** [comment]
> I appreciate your interest in the project. Unfortunately, I've implemented the whole project with drizzle and there's no example for using Prisma. But hope these guides can help you.
> 
> https://www.prisma.io/docs/orm/more/migrating-to-prisma/migrate-from-drizzle https://www.prisma.io/docs/orm/more/comparisons/prisma-and-drizzle

Alright thanks for the info sharing
